#! /bin/sh
# /etc/init.d/ZowiInit

### BEGIN INIT INFO
# Provides:		ZowiInit
# Required-Start:	$all
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Script arranque calibracion Zowi
# Description:		Script para arranque programa programa python calibracion Zowi
### END INIT INFO

case "$1" in
	start)
		echo "Starting ZowiInit"
		#/usr/bin/python /home/pi/zowi/python/main.mysql.py
		# & para ejecutar script de forma paralela
		/etc/init.d/running.sh&
		# script con el checker del avrdude
		/etc/init.d/check.avrdude.sh&
		
		;;
	stop)
		echo "Stopping ZowiInit"
		;;
	*)
		echo "Using mode: /etc/init.d/ZowiInit {start|stop}"
		exit 1
		;;
esac

exit 0
